name = "master-clash-backend"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "CHECKPOINTS_DB"
database_name = "master-clash-frontend"
database_id = "aab16eeb-a375-490b-ad1e-cd092cd9f4bb"

[[r2_buckets]]
binding = "master_clash_assets"
bucket_name = "master-clash-assets"
